/**
* Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
*/

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  guidesSidebar: [
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          case "de": return "Erste Schritte";
          default: return "First steps";
        }
      })(),
      defaultStyle: true,
    },
    'welcome',
    'abuse-report',
    'firststeps-register',
    'firststeps-register2',
    'preorders',
    'necesse-firststeps-connect',
    'necesse-troubleshooting-common-issues',
    'necesse-firststeps-dashboard'

  ]
  
};

export default sidebars;